name: discover_egypt
description: All-in-one tourism app for Egypt - Hotels, Tours, Cars, Food
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10
  google_fonts: ^6.3.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  confetti: ^0.7.0
  flutter_stripe: ^11.5.0
  shared_preferences: ^2.3.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  connectivity_plus: ^6.1.5
  intl: ^0.20.1
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  radio_group_v2: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
